spring.application.name=kpis-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/kpis_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:kpis_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kpis_pass}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
