apiVersion: v1
kind: Secret
metadata:
  name: grupo-cordillera-db-secret
  namespace: grupo-cordillera
type: Opaque
stringData:
  KPIS_DB_PASSWORD: kpis_pass
  USER_DB_PASSWORD: user_pass
  REPORT_DB_PASSWORD: report_pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grupo-cordillera-config
  namespace: grupo-cordillera
data:
  KPIS_DB_NAME: kpis_db
  KPIS_DB_USER: kpis_user
  USER_DB_NAME: user_db
  USER_DB_USER: user_user
  REPORT_DB_NAME: report_db
  REPORT_DB_USER: report_user
  AUTH_API_URL: http://auth-service:8080/api/auth
  KPIS_API_URL: http://kpis-service:8081/api/kpis
  USER_API_URL: http://user-service:8082/api/users
  REPORT_API_URL: http://report-service:8082/api/reports
  ALLOWED_ORIGINS: http://localhost,http://localhost:5173,http://grupo-cordillera.local
  GLITCHTIP_DSN: "http://a02d1b115e3f493b83c29c53d5ce95d5@host.docker.internal:8000/2"
