apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: grupo-cordillera
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
  SPRING_DATASOURCE_USERNAME: user_user
  GLITCHTIP_DSN: ""
