apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
  namespace: grupo-cordillera
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://report-db:5432/report_db
  SPRING_DATASOURCE_USERNAME: report_user
  GLITCHTIP_DSN: ""
