apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: grupo-cordillera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: grupo-cordillera-report-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: report-service-config
            - secretRef:
                name: report-service-secret
          readinessProbe:
            httpGet:
              path: /api/reports/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/reports/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
