apiVersion: v1
kind: ConfigMap
metadata:
  name: kpis-service-config
  namespace: grupo-cordillera
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://kpis-db:5432/kpis_db
  SPRING_DATASOURCE_USERNAME: kpis_user
  GLITCHTIP_DSN: "http://995cfa69b10d49749463e2e75a2ce9a4@host.docker.internal:8000/3"
